version: "3.7"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    hostname: localstack
    networks:
      - localstack-net
    ports:
      # - "4566:4566" # Default all services run on 4566
      - "5000:5000"
    environment:
      - EDGE_PORT=5000 #Default edge port is 4565 for all services, change here and above Port section if you want to customize it
      - SERVICES=serverless,sqs # serverless = (apigatway,cloudformation,cloudwatch,dynamodb,iam,sts,kinesis,lambda,s3) ; add others like sqs,sns,events on needed basis
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-./data}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
  dynamodb-ui:
    container_name: "dynamodb-admin"
    image: aaronshaf/dynamodb-admin:latest
    networks:
      - localstack-net
    ports:
      # - "8000:8000"
      - "8001:8001"
    environment: 
      - DYNAMO_ENDPOINT=http://localstack:5000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net