version: "3.7"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    hostname: localstack
    networks:
      - localstack-net
    ports:
      # - "4566:4566" # Default all services run on 4566
      - "5000:5000"
    environment:
      - SERVICES=s3,sqs,lambda,cloudformation,sts,iam,cloudwatch,apigateway,events # Add other services if you are interested
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - EDGE_PORT=5000 #Default port is 4565 for all services, change here and above Port section if you want to customize it
      # - PORT_WEB_UI=8080 Localstack UI is deprecated.  Alternative UI should be used instead.
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-./data}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net