FROM ubuntu:20.04

# FROM ubuntu:$RELEASE
ENV container docker
ENV PATH "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
RUN apt-get update &&\
  DEBIAN_FRONTEND=noninteractive\
  apt-get install -y fuse snapd snap-confine squashfuse sudo init &&\
  apt-get clean &&\
  dpkg-divert --local --rename --add /sbin/udevadm &&\
  ln -s /bin/true /sbin/udevadm
RUN systemctl enable snapd
VOLUME ["/sys/fs/cgroup"]
STOPSIGNAL SIGRTMIN+3

CMD ["/sbin/init"]

# RUN apt update && \
#   apt -y upgrade && \
#   apt install -y snapd

# COPY . 
# # RUN snap install commandeer

# # COPY service /opt/my/service

# # WORKDIR /opt/my/service

# # RUN adduser --disabled-password --gecos '' appuser\  
# #   && chown -R appuser:appuser /opt/my/service

# # USER appuser
# # EXPOSE 9000
# # ENTRYPOINT ["commandeer"]
# CMD ["bash"]